### ISSUE TITLE
饿了么账号格式？

### ISSUE THREAD

**Issue by fulianbaoBear** [ClassmateLin/scripts_v2#9]
如题，大佬解惑~

**Comment by ClassmateLin** [comment]
[
"1xxxxx",
"2xxxx"
]

**Comment by stayforever99** [comment]
请教日志这样是什么原因？
Traceback (most recent call last):
  File "/scripts/app/jd/jd_dove_polite.py", line 141, in <module>
    run_jd(JdDovePolite)
  File "/scripts/app/jd.py", line 137, in run_jd
    d['account'] = d.get('remark', None) if d.get('remark', None) else urllib.parse.unquote(d['pt_pin'])
KeyError: 'pt_pin'
cookie格式问题？原来是好好的

**Comment by fulianbaoBear** [comment]
谢谢~

**Comment by ClassmateLin** [comment]
> 请教日志这样是什么原因？ Traceback (most recent call last): File "/scripts/app/jd/jd_dove_polite.py", line 141, in run_jd(JdDovePolite) File "/scripts/app/jd.py", line 137, in run_jd d['account'] = d.get('remark', None) if d.get('remark', None) else urllib.parse.unquote(d['pt_pin']) KeyError: 'pt_pin' cookie格式问题？原来是好好的

检查一下cookie。

**Comment by stayforever99** [comment]
好的  谢谢
